# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NomadPortForward < Formula
  desc "Forward ports from a Nomad job to a local machine"
  homepage "https://github.com/Mongey/nomad-port-forward"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Mongey/nomad-port-forward/releases/download/v0.2.0/nomad-port-forward_Darwin_x86_64.tar.gz"
      sha256 "5e03e79fcb6d2f05469191d0318481adb9ead7cf11413c721765e50e832502dc"

      def install
        bin.install "nomad-port-forward"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Mongey/nomad-port-forward/releases/download/v0.2.0/nomad-port-forward_Darwin_arm64.tar.gz"
      sha256 "d933aa676f9a4426a83eb551e8ec7ee00ac99225633c5e5102362210859baf80"

      def install
        bin.install "nomad-port-forward"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Mongey/nomad-port-forward/releases/download/v0.2.0/nomad-port-forward_Linux_x86_64.tar.gz"
      sha256 "18baf2b62b1886e6a8a624110e39b9c8703583b02168892487c3a1efd94f1314"
      def install
        bin.install "nomad-port-forward"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Mongey/nomad-port-forward/releases/download/v0.2.0/nomad-port-forward_Linux_arm64.tar.gz"
      sha256 "3b16ef5a1bdc3e07a7c66ea22619a33fe1d2f8076ee0334cadd3acf7607e464e"
      def install
        bin.install "nomad-port-forward"
      end
    end
  end
end
